apiVersion: apps/v1
kind: Deployment
metadata: 
  name: item-deployment
  labels:
    app: item-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-api
  template:
    metadata:
      name: 
        labels:
          app: item-api
      spec:
        containers:
          - name: item-api
            image: link-da-imagem-no-aws
            ports:
              - containerPort: 80
